### ISSUE TITLE
Error in Lite.php

### ISSUE THREAD

**Issue by edrobinson** [parkerj/Liten#1]
I get this error on startup:

Parse error: syntax error, unexpected '[' in C:\wamp\www\Liten-master\Liten\Liten.php on line 48

Yet when I try to edit Lite.php, line 48 is:

protected static $_apps = [];

Unable to procede

**Comment by nomadicjosh** [comment]
Sorry about that. It is specified on the doc site but not on GitHub. The minimum php version requirement is 5.4.

**Comment by edrobinson** [comment]
Joshua,

I am using a WAMP stack with PHP 5.3...

Ed

On Tue, Mar 31, 2015 at 3:46 PM, Joshua Parker notifications@github.com
wrote:

> Sorry about that. It is specified on the doc site but not on GitHub. The
> minimum php version requirement is 5.4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/7mediaws/Liten/issues/1#issuecomment-88260543.

## 

Ed Robinson
edrobinsonjr@gmail.com
Phone: 208-376-2680

**Comment by nomadicjosh** [comment]
Can you upgrade the php version?

**Comment by edrobinson** [comment]
I'll see what I can do.

On Tue, Mar 31, 2015 at 6:18 PM, Joshua Parker notifications@github.com
wrote:

> Can you upgrade the php version?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/7mediaws/Liten/issues/1#issuecomment-88291799.

## 

Ed Robinson
edrobinsonjr@gmail.com
Phone: 208-376-2680

**Comment by nomadicjosh** [comment]
I did find this: http://forum.wampserver.com/read.php?2,124935

Also, I highly recommend AMPPS. It has a WAMP, MAMP, and LAMP stack and it is very easy to switch PHP versions. AMPPS can be found here: http://www.ampps.com/

**Comment by edrobinson** [comment]
I tried to install ampps but could not get apache to start. No error
messages anyplace.

Looking at your code I cannot see anything that should need php 5.4. It all
looks pretty straight forward.

The error I see references a specific line in a specific file. However,
there is no pipe character in that spot.

I'll look some more.

Ed

On Tue, Mar 31, 2015 at 8:00 PM, Joshua Parker notifications@github.com
wrote:

> I did find this: http://forum.wampserver.com/read.php?2,124935
> 
> Also, I highly recommend AMPPS. It has a WAMP, MAMP, and LAMP stack and it
> is very easy to switch PHP versions. AMPPS can be found here:
> http://www.ampps.com/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/7mediaws/Liten/issues/1#issuecomment-88311808.

## 

Ed Robinson
edrobinsonjr@gmail.com
Phone: 208-376-2680

**Comment by edrobinson** [comment]
Joshua,

I have gone through your code and changed all "[]" to "array()" and short
open tags in the default layout to long open tags and I have the framework
working under php 5.3.13.

I will forward a copy to you after I mark all of my changes.

On Wed, Apr 1, 2015 at 3:38 PM, Ed Robinson edrobinsonjr@gmail.com wrote:

> I tried to install ampps but could not get apache to start. No error
> messages anyplace.
> 
> Looking at your code I cannot see anything that should need php 5.4. It
> all looks pretty straight forward.
> 
> The error I see references a specific line in a specific file. However,
> there is no pipe character in that spot.
> 
> I'll look some more.
> 
> Ed
> 
> On Tue, Mar 31, 2015 at 8:00 PM, Joshua Parker notifications@github.com
> wrote:
> 
> > I did find this: http://forum.wampserver.com/read.php?2,124935
> > 
> > Also, I highly recommend AMPPS. It has a WAMP, MAMP, and LAMP stack and
> > it is very easy to switch PHP versions. AMPPS can be found here:
> > http://www.ampps.com/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/7mediaws/Liten/issues/1#issuecomment-88311808.
> 
> ## 
> 
> Ed Robinson
> edrobinsonjr@gmail.com
> Phone: 208-376-2680

## 

Ed Robinson
edrobinsonjr@gmail.com
Phone: 208-376-2680

**Comment by nomadicjosh** [comment]
Yes, those are 5.4 features because I am coding this framework for a minimal of 5.4.
